# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_ZF_DEVICE_IMU660RA) += zf_device_imu660ra.o
zf_device_imu660ra-objs := zf_device/zf_device_imu660ra.o  zf_device/zf_device_config.o

obj-$(CONFIG_ZF_DEVICE_IMU963RA) += zf_device_imu963ra.o
zf_device_imu963ra-objs := zf_device/zf_device_imu963ra.o

obj-$(CONFIG_ZF_DRIVER_ATIM) += zf_driver_atim.o
zf_driver_atim-objs := zf_driver/zf_driver_atim.o

obj-$(CONFIG_ZF_DRIVER_ENCODER) += zf_driver_encoder.o
zf_driver_encoder-objs := zf_driver/zf_driver_encoder.o 

obj-$(CONFIG_ZF_DRIVER_GPIO) += zf_driver_gpio.o
zf_driver_gpio-objs := zf_driver/zf_driver_gpio.o 

obj-$(CONFIG_ZF_DRIVER_GTIM) += zf_driver_gtim.o
zf_driver_gtim-objs := zf_driver/zf_driver_gtim.o

obj-$(CONFIG_ZF_DRIVER_PWM) += zf_driver_pwm.o
zf_driver_pwm-objs := zf_driver/zf_driver_pwm.o 